{
 "title": "Time Window Template Detail",
 "time": { "from": "2020-06-24T21:51:30.000Z", "to": "2020-06-24T22:18:20.000Z" },
 "templating": {
  "list": [
   { "name": "template_table", "query": "postgres" },
   { "name": "template_version", "query": "postgres" },
   { "name": "time_window_id", "query": "postgres" },
   { "name": "template_id", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Template for:    $template_table",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  template\nFROM templates\nwhere id = '$template_id' and version = $template_version"
    }
   ]
  },
  {
   "title": "Time Window Record Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT * FROM $template_table WHERE time_window_id = $time_window_id and template_version = '$template_version';\n"
    }
   ]
  },
  {
   "title": "Random Log Examples for Template $template_table",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\nrecord\nFROM\n  templates_example\nWHERE\n template_id = '$template_id' and template_version = $template_version\n"
    }
   ]
  }
 ]
}